apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-pipeline
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ci-cd-pipeline
  template:
    metadata:
      labels:
        app: ci-cd-pipeline
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
