version: 2.1
orbs: 
  slack: circleci/slack@4.9.3
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # we want a new Docker
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
    steps:
      - checkout
      - run:
          name: Build Image
          command: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

